### ISSUE TITLE
Unable to change standard resource to a location resource with the settings tab

### ISSUE THREAD

**Issue by muzzwood** [digitalpenguin/LocationResources#1]
A bug that slipped through in development.

LocationResources can be created ok via the resource tree.
Creating a new standard resource and changing the resource type to 'Location' on the settings tab before clicking save also works.

Problem is, if a default resource has already been created (it has been saved at least once), then if you try to change the resource type to 'Location' via the settings tab, it won't save.
Most likely a problem with the update processor.

**Comment by Jako** [comment]
The initial issue: $this->profile is null if you change it to LocationResource after saving. 

Duplicating a LocationResource is not possible for the same reason.

**Comment by muzzwood** [comment]
Cheers @jako - will look into it over the next couple of days.

**Comment by muzzwood** [comment]
Fixed the issue when changing an existing resource into a Location Resource via the settings tab.
Still a problem duplicating Location Resources though - apparently unrelated.

**Comment by muzzwood** [comment]
Duplication needed its own function within an extension of xpdoSimpleObject. Hopefully there are no more worries with this! ;)
Closing.

**Comment by Jako** [comment]
Thanks for your fixes.
