### ISSUE TITLE
Database update missed in upgrade path?

### ISSUE THREAD

**Issue by jcdm** [digitalpenguin/LocationResources#11]
I recently updated to 1.2.1 from something before 1.2.

In the manager and in the front end I was seeing no map data. The front end was showing 'Error: resource did not contain an extended profile (ID:178)' while the manager was just coming up blank fields.

I could see the profile data being written the database table with each save but nothing seemed to be able to read it.

Checking the manager log I found the following:
`[2017-07-11 12:37:33] (ERROR @ /www-root/core/xpdo/om/xpdoobject.class.php : 240) Error 42S22 executing statement: 
Array
(
    [0] => 42S22
    [1] => 1054
    [2] => Unknown column 'LocationProfile.marker_link_text' in 'field list'
)`

Which indicated that marker_link_text was missing from the database as a field. I added it manually and everything has 'snapped back' into place.

I wanted to flag this because somewhere in my upgrade path the field missed out on being added to the table so if that's something controllable from this end, then that should be patched somewhere in the next release.

**Comment by muzzwood** [comment]
Thanks for the report Josh. I've upgraded a few installs from 1.1.2 to 1.2.1 and didn't experience the issue. Is it possible your version was prior to 1.1.2?

**Comment by jcdm** [comment]
Yep - I was coming from 1.0.1 (which sounded like a long way behind until I realised that was only installed in March).

Anything else I may have missed that I should check that you can think of off the top of your head?

**Comment by muzzwood** [comment]
Hmmm it's possible I missed something in the packaging back then. I'll have a look at a script checking the db columns for the next release. 

If anyone else experienced this and comes here looking, please leave a comment letting me know you were also affected. Cheers.

**Comment by muzzwood** [comment]
I think this was just with an early version. It doesn't seem to have been a recurring problem so will close for now. Cheers!
