### ISSUE TITLE
Create lexicon strings reversed

### ISSUE THREAD

**Issue by Mark-H** [digitalpenguin/LocationResources#12]
v1.2.1

![schermafbeelding 2017-07-11 om 15 58 11](https://user-images.githubusercontent.com/312944/28071938-bf3400f2-6651-11e7-846c-cd21303875a6.jpg)

![schermafbeelding 2017-07-11 om 15 58 21](https://user-images.githubusercontent.com/312944/28071949-c5928c02-6651-11e7-87ff-fff76d3801e5.jpg)

There's very little logic to why MODX has "Create a ... here" for one and not the other, but might as well try to be consistent with it for now :P

**Comment by muzzwood** [comment]
Oooof hadn't noticed that. Cheers, I'll get that patched soon.

**Comment by muzzwood** [comment]
Updated! Thanks.
