### ISSUE TITLE
Using the values on the frontend (longitude, title, link, etc...)

### ISSUE THREAD

**Issue by robliberty** [digitalpenguin/LocationResources#13]
Hi,

Is there a way to call the values on the frontend in text form? Something like [[+locationResourcesMap:longitude]] would be cool. Thanks!

**Comment by muzzwood** [comment]
Hi @itsmerobliberty 
Are you able to use the placeholders like in the default JS chunk?
https://github.com/digitalpenguin/LocationResources/blob/master/core/components/locationresources/elements/chunks/locationresourcesscript.chunk.tpl

It should be [[+lr.map_lng]] or [[+lr.marker_lng]] depending on which one you're after.
