### ISSUE TITLE
Have the map centre on the marker by default

### ISSUE THREAD

**Issue by jcdm** [digitalpenguin/LocationResources#6]
When editing a location in the manager, to centre exactly on the marker seems to be a case of setting the marker and then copying and pasting the lat/long from the marker to the map fields.

I don't mind two separate lat/long values for map and marker because it allows for flexibility but it would be nice to have a 'centre map to marker' button or something to make it easy for clients to synchronise those values quickly.

**Comment by muzzwood** [comment]
I think it's important to save the map and marker coordinates separately however the button is a good idea. Will try and get this implemented at the same time I add search since the layout will need to change.

**Comment by muzzwood** [comment]
Button added for 1.2.0
