### ISSUE TITLE
Make it compatible with ContentBlock

### ISSUE THREAD

**Issue by julienstuder** [digitalpenguin/LocationResources#9]
locationResource type is not compatible with ContentBlock. 

here is the docs:
https://docs.modmore.com/en/ContentBlocks/v1.x/Custom_Resources.html

thanks.

**Comment by muzzwood** [comment]
I've barely touched ContentBlocks so far but this should give me a chance to get my hands dirty. ;)

**Comment by julienstuder** [comment]
if you need access to my install/manager to make it, with pleasure.
but you can also get CB as demo from Modmore i think.

**Comment by muzzwood** [comment]
Hi Julien, did you try adding a Location to the `contentblocks.accepted_resource_types` system setting for Content Blocks?
According to the docs it *should* work. If not, I'll get at it soon.

**Comment by julienstuder** [comment]
Hi, wow thanks for your answer... i had written LocationResource in this system setting... !
so it works with CB by default, cool !

**Comment by julienstuder** [comment]
When i view the CB ressource in front-end, no map is displayed, and i get a js error:
 in this ligne 
 `{lat: 37,94238, lng: 11,130402}  Uncaught SyntaxError: Unexpected token ,
`

```
<script>
    var lrMap193 = new google.maps.Map(document.getElementById('lr_map193'), {
        zoom: 3,
        center: {lat: 37,94238, lng: 11,130402}
    });
    if (1) {
        var marker = new google.maps.Marker({
            position: {lat: 27,585508, lng: 7,262517},
            draggable: false,
            clickable: true,
            map: lrMap193
        });
        var lrTitle = '';
        var lrDesc = '';
        var lrLink = '';
        var lrContent = '';
        if (lrTitle.length > 0) {
            lrContent += "<h4></h4>";
        }
        if (lrDesc.length > 0) {
            lrContent += "<p></p>";
        }
        if (lrLink.length > 0) {
            lrContent += "<a href=''>Click Here</a>";
        }
        if (lrContent.length > 0) {
            marker.info = new google.maps.InfoWindow({
                content: lrContent
            });
            marker.info.open(lrMap193, marker);
            google.maps.event.addListener(marker, 'click', function() {
                marker.info.open(lrMap193, marker);
            });
        }
    }
    google.maps.event.addDomListener(window, "resize", function() {
        var center = lrMap193.getCenter();
        google.maps.event.trigger(lrMap193, "resize");
        lrMap193.setCenter(center);
    });
</script>
```

**Comment by muzzwood** [comment]
Is that using `[[locationResourcesMap]]` without any parameters or is it a custom JS chunk?

**Comment by julienstuder** [comment]
yes only with  `[[locationResourcesMap]]` !
But now i remember that my manager is not in english, and that it could have issue on that.
Right ? we talked about it on Slack...

**Comment by julienstuder** [comment]
that the coma instead of a dot comes from the manager is not in english or something like that ?

**Comment by muzzwood** [comment]
Yeah you're probably right, it looks like it's getting confused by the commas instead of the decimal points. So the same code works fine if not on the same resource as content blocks? (just to make sure)

**Comment by julienstuder** [comment]
if I deactivate ContentBlock, the bug remains.
I think it comes from my manager not being in english.
maybe you could add a system setting to set the use of a dot ?

**Comment by muzzwood** [comment]
Fixed in next patch. :)

**Comment by Mark-H** [comment]
As of ContentBlocks v1.7, LocationResources (`Location` class key) is added to the supported list by default. Nice work @digitalpenguin!

**Comment by muzzwood** [comment]
Cheers Mark!
